baseURL = "https://nonante-dix.netlify.app/"
# title = "Hugo Themes"
author = "Bibo Manu"
copyright = "Copyright © 2022, Nonante-dix; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-paper"
title = "90X"

[params]
  color = 'linen'

  twitter = 'digitaldre_am'
  github = 'nonante-dix'
  instagram = 'digitaldre_am'

  avatar = ''
  name = ''
  bio = 'La Digitalistaion pour tous'

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
